name: ORAL

on:
    workflow_dispatch:

permissions:
    contents: read
    actions: read
    checks: write

jobs:
    preparation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Introduction
              run: sleep 5
            - name: CI
              run: sleep 2
    ci:
        runs-on: ubuntu-latest
        needs: [preparation]
        steps:
            - uses: actions/checkout@v4

            - name: Configure Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Run npm ci
              run: npm ci
            
            - run: lint
              name: npm run lint:fix
